batch_size: 64
learning_rate: 0.001
num_epochs: 50
patience: 5
hidden_layers: [2048, 2048]
dropout_rate: 0.3

anchors_num: 350
train_path: './data/train/train.npz'
test_path: './data/test/test.npz'

pad: False
standardize: False
normalize: False

anchors_method: 'pca'
use_relative: True
model_mode: 'affine'
model_save_path: './models/exp1.pth'
input_dim: 1024
output_dim: 1536